Port to GTK4
elementary/onboarding pull request #152
Opened 2021-12-21 02:11 UTC by ZenitsuDev

Port to GTK4 to see where we are blocked

Depends on Granite

Changes to be made:
- [ ] Replace instances of Grid where Box with pack_start is preferrable for smoother transition
- [ ] Replace expand with hexpand or vexpand
- [ ] Replace add with child property
- [ ] Replace margin with specific margins

2021-12-26 20:24 UTC, danrabbit commented on src/Switcher.vala
> +        base.present ();
Since the behavior here is a bit different and GTK4 shows children by default, this should probably be after `if (!has_enough_children)` since we don't need to present if that returns true

2021-12-27 00:10 UTC, ZenitsuDev commented on src/Switcher.vala
> +        base.present ();
okay. I will try it. thanks!

2022-01-09 19:24 UTC, danrabbit commented on src/MainWindow.vala
> +public class Onboarding.MainWindow : Adw.ApplicationWindow {
We probably don't need to use an Adwaita window here since Gtk.ApplicationWindow will crop rounded corners now

2022-01-09 19:24 UTC, danrabbit commented on src/MainWindow.vala
> +        next_button.get_style_context ().add_class (Granite.STYLE_CLASS_SUGGESTED_ACTION);
You can replace `get_style_context ().add_class` with `add_css_class`
```suggestion
        next_button.add_css_class (Granite.STYLE_CLASS_SUGGESTED_ACTION);
```

2022-01-09 19:58 UTC, ZenitsuDev commented on src/MainWindow.vala
> +public class Onboarding.MainWindow : Adw.ApplicationWindow {
Okay. I will change it. Thanks!

2022-01-12 00:24 UTC, danrabbit requested changes
Lots of good progress, left a few comments!

I'm not sure how to deal with the image size yet on the style view. Maybe we could set them in CSS. background image can take a URL property like `url("resource:///io/elementary/onboarding/appearance-default.svg")`

2022-01-12 00:24 UTC, danrabbit commented on src/PageChecker.vala
> +        }
You need to call `update_opacity` after assigning a page number

```suggestion
        for (var item_count = 0; item_count < carousel.get_n_pages (); item_count++) {
            if (carousel.get_nth_page (item_count) == page) {
                page_number = item_count;
                break;
            }
        }

        update_opacity ();
```

2022-01-12 00:40 UTC, ZenitsuDev commented on src/Views/EarlyAccessView.vala
> +        var title_label = new Gtk.Label (_("Major Known Issues"));
Okay! I will. Thanks

2022-01-12 00:41 UTC, ZenitsuDev commented on src/PageChecker.vala
> +        }
oh yeah right. Thanks!

2022-01-12 09:57 UTC, ZenitsuDev commented
Okay I will search for how it can be done. thanks!

2022-01-12 21:37 UTC, danrabbit reviewed
I pushed a commit to fix the style view!

2022-01-12 21:37 UTC, danrabbit commented on src/MainWindow.vala
> +        // next_finish_overlay.set_overlay_pass_through (next_label, true);
I'm not sure what these were for in GTK3, but it seems like we don't need this anymore, so it can just be removed

2022-01-12 21:37 UTC, danrabbit commented on src/Switcher.vala
>      public override void show () {
We actually rely on this box to exist now to provide the layout, so I think we should remove this override altogether. It's not really necessary anyways it seems

2022-01-13 05:47 UTC, ZenitsuDev commented
Thanks for the fixes! @danrabbit

2022-01-13 19:21 UTC, danrabbit approved these changes
This looks good to me. I think I'm happy to merge this if you want to mark it as ready. Nice work :tada:

2022-01-13 22:21 UTC, ZenitsuDev commented
Thanks @danrabbit

2022-01-13 23:00 UTC, merged

2022-01-13 23:00 UTC, danrabbit commented
Thank you! Fantastic job!