Replace Grid with Box for simplicity and easier GTK4 Transition
elementary/onboarding pull request #157
Opened 2021-12-24 07:34 UTC by ZenitsuDev

There are `Gtk.Grid`s with `add` that can be replaced with `Box` and `pack_start`, so that in GTK4 Transition we can just replace `pack_start` with `append`.

2021-12-26 20:20 UTC, danrabbit requested changes
It looks like Grid and Box behave quite differently here in how they align their children. So, to keep the same alignment, it would probably be better to use Gtk.Grid with `attach` in some of these cases

2021-12-26 20:20 UTC, danrabbit commented on src/Views/WelcomeView.vala
> +            var box = new Gtk.Box (Gtk.Orientation.HORIZONTAL, 0);
It seems like this is a case where the horizontal alignment is broken by box:

### Box:
![Screenshot from 2021-12-26 12 18 09](https://user-images.githubusercontent.com/7277719/147419153-be47b811-7b3f-4151-8869-22275ae70a56.png)

### Grid:
![Screenshot from 2021-12-26 12 17 35](https://user-images.githubusercontent.com/7277719/147419155-ce215f8c-dfde-439d-a90b-c84bfde6bd44.png)

2021-12-26 20:20 UTC, danrabbit commented on src/Views/AbstractOnboardingView.vala
> +        var header_area = new Gtk.Box (Gtk.Orientation.VERTICAL, 6) {
You can see here how Box really expands the children to fill space, so we get titles at a different y height on every view:

### Box:
![Screenshot from 2021-12-26 12 18 16](https://user-images.githubusercontent.com/7277719/147419173-f79e6cf5-6327-486a-bfbf-d769d16c6ae7.png)

### Grid:
![Screenshot from 2021-12-26 12 18 38](https://user-images.githubusercontent.com/7277719/147419171-3a90f92e-eaed-46c9-b1ad-861d71c87c67.png)

2021-12-27 00:11 UTC, ZenitsuDev commented on src/Views/AbstractOnboardingView.vala
> +        var header_area = new Gtk.Box (Gtk.Orientation.VERTICAL, 6) {
oh, I didn't notice it. Let me change that. Thanks!

2021-12-27 01:18 UTC, ZenitsuDev commented
@danrabbit thanks! I think the fix would be to specify the packing arguments as shown in https://valadoc.org/gtk+-3.0/Gtk.Box.html 
`public void pack_start (Widget child, bool expand = true, bool fill = true, uint padding = 0)`

2021-12-27 01:44 UTC, ZenitsuDev commented on src/Views/WelcomeView.vala
> +            var box = new Gtk.Box (Gtk.Orientation.HORIZONTAL, 0);
Hi! I tried declaring a `halign` property for the ImageLinkButtons and this is how they look like after. However, I am not able to confirm if it did the trick because my eyes have problem noticing symmetry. 
![Screenshot from 2021-12-27 09-40-11](https://user-images.githubusercontent.com/73321827/147425989-f1ed8936-499b-4b6e-8641-f34a7041a342.png)
Did it did the trick? or should I just use Grid instead? Thanks

2021-12-27 01:49 UTC, ZenitsuDev commented on src/Views/AbstractOnboardingView.vala
> +        var header_area = new Gtk.Box (Gtk.Orientation.VERTICAL, 6) {
I did not notice but `pack_start` sets the expand and fill properties to `true` by default. I'll try declaring it to false first

2021-12-27 02:09 UTC, ZenitsuDev commented on src/Views/AbstractOnboardingView.vala
> +        var header_area = new Gtk.Box (Gtk.Orientation.VERTICAL, 6) {
I set the expand argument at pack_start to false to avoid this problem
![Screenshot from 2021-12-27 10-07-33](https://user-images.githubusercontent.com/73321827/147427234-ac1003a2-c9c5-4a7b-acd7-5d8265872af9.png)

2022-01-02 11:19 UTC, ZenitsuDev commented
I'll redo this so I'll close for now

2022-01-02 11:19 UTC, closed without merging