Add screenshot files cleanup option to Housekeeping
elementary/onboarding pull request #208
Opened 2023-05-07 22:56 UTC by Antolius

Resolve #189 

Add check button for enabling screenshot files cleanup to Housekeeping view. Add a custom icon for screenshot files.

Mirrors changes to the switchboard plugin proposed in [this PR](https://github.com/elementary/switchboard-plug-security-privacy/pull/141).

![Screenshot from 2023-05-08 00 52 18](https://user-images.githubusercontent.com/5374391/236706539-559e1da8-e959-451e-bfa7-e1b350426fdb.png)

2023-05-07 23:02 UTC, Antolius commented on data/folder-screenshots-icon/24.svg
I copied this icon from the [switchboard pull request](https://github.com/elementary/switchboard-plug-security-privacy/pull/141). If having the same custom icon in 2 different repositories is not OK I could:

1. Pull it into [Icons](https://github.com/elementary/icons) repo and reuse it in both applications. Although I'm not sure how appropriate that would be considering that this is not a standard icon.
2. Load switchboard-plug-security-privacy icons here and just reuse it that way.

2023-06-01 17:05 UTC, danirabbit requested changes
Nice work! Just a couple of changes

2023-06-01 17:05 UTC, danirabbit commented on data/folder-screenshots-icon/24.svg
I think the precedent we have so far is in keyboard settings we gresource the Screenshots app icon, which you can find here: https://github.com/elementary/screenshot/blob/master/data/icons/24.svg

2023-06-01 17:05 UTC, danirabbit commented on data/io.elementary.onboarding.gresource.xml
> +        <file alias="24x24/apps/folder-screenshots-icon.svg" compressed="true" preprocess="xml-stripblanks">folder-screenshots-icon/24.svg</file>
There's actually a namespacing trick we can do to load these into the icons path automatically:
```suggestion
</gresource>
<gresource prefix="io/elementary/onboarding/icons">
    <file alias="24x24@2/apps/folder-screenshots-icon.svg" compressed="true" preprocess="xml-stripblanks">folder-screenshots-icon/24.svg</file>
    <file alias="24x24/apps/folder-screenshots-icon.svg" compressed="true" preprocess="xml-stripblanks">folder-screenshots-icon/24.svg</file>
```

2023-06-01 17:05 UTC, danirabbit commented on src/Application.vala
> +        Gtk.IconTheme.get_for_display (Gdk.Display.get_default ()).add_resource_path ("/io/elementary/onboarding");
We don't actually need this if we namespace the gresource to the icons path
```suggestion
```

2023-06-02 17:32 UTC, Antolius commented on src/Application.vala
> +        Gtk.IconTheme.get_for_display (Gdk.Display.get_default ()).add_resource_path ("/io/elementary/onboarding");
One potential problem: for this to work GTK application_id needs to match, and it previously did not.
I changes it in [this commit](https://github.com/elementary/onboarding/pull/208/commits/d9016162c6301d5183c8b8ec5362fbb45442618f#diff-f4e5d48d751c670a8575715da1cb0a0976532427a8b6143c7fdede415a33ba6cR8), but I'm not sure if this is 100% safe to do. In my testing it works OK, but there might be some backwards compatibility issue I'm not aware of.

2023-06-02 18:17 UTC, danirabbit approved these changes
Looks good, works as expected. Thanks for fixing the app ID! Nice work :)

2023-06-02 18:18 UTC, merged